"use client";
import { useEffect, useMemo, useState, type FormEvent } from "react";
import { ArrowDown, ArrowLeft, ArrowUpRight, AtSign, Check, ChevronDown, CircleHelp, Clock3, Inbox, MessageCircleMore, MoreHorizontal, Paperclip, Plus, Search, Send, Settings2, ShieldCheck, Smile, Sparkles, Tag, Users, X } from "lucide-react";

type Message = { id: string; from: string; time: string; body: string; kind?: "note" };
type Ticket = { id: string; name: string; email: string; subject: string; preview: string; time: string; initials: string; color: string; unread: boolean; priority: boolean; label: string; messages: Message[] };
const seed: Ticket[] = [
 {id:"RL-2841",name:"Maya Chen",email:"maya.chen@example.com",subject:"My workspace disappeared after upgrading",preview:"I upgraded to Pro this morning, but now my whole team workspace is gone…",time:"4m",initials:"MC",color:"#d5a278",unread:true,priority:true,label:"Billing",messages:[{id:"m1",from:"Maya Chen",time:"10:42 AM",body:"Hi there — I upgraded to Pro this morning, but now my whole team workspace is gone. I can still see my personal projects, but our shared studio board has completely disappeared. We have a client presentation this afternoon, so any help getting it back would be amazing."},{id:"m2",from:"Maya Chen",time:"10:44 AM",body:"I paid with the same email I use to log in. The receipt came through, if that helps."}]},
 {id:"RL-2840",name:"Jon Bell",email:"jon.bell@example.com",subject:"Can I export my project history?",preview:"Our team is moving to a new planning tool next quarter. Is there a way to…",time:"18m",initials:"JB",color:"#799a94",unread:true,priority:false,label:"How-to",messages:[{id:"m3",from:"Jon Bell",time:"10:28 AM",body:"Our team is moving to a new planning tool next quarter. Is there a way to export our full project history, including comments and attachments?"}]},
 {id:"RL-2839",name:"Priya Nair",email:"priya.nair@example.com",subject:"Invite link says it has expired",preview:"I sent a workspace invite to my colleague yesterday and she just got…",time:"42m",initials:"PN",color:"#9b86b6",unread:false,priority:false,label:"Account access",messages:[{id:"m4",from:"Priya Nair",time:"9:54 AM",body:"I sent a workspace invite to my colleague yesterday and she just got a message that the link has expired. Could you send a fresh invite?"}]},
 {id:"RL-2838",name:"Noah Williams",email:"noah.w@example.com",subject:"The mobile app keeps signing me out",preview:"Every time I switch away from the app for a little while, I have to sign in…",time:"1h",initials:"NW",color:"#7e93b7",unread:false,priority:false,label:"Bug report",messages:[{id:"m5",from:"Noah Williams",time:"9:23 AM",body:"Every time I switch away from the app for a little while, I have to sign in again. I'm on the latest iOS version."}]},
 {id:"RL-2837",name:"Elena Rossi",email:"elena.rossi@example.com",subject:"Thank you for sorting the invoice",preview:"Just wanted to say the updated invoice came through. Everything looks…",time:"2h",initials:"ER",color:"#be8c89",unread:false,priority:false,label:"Billing",messages:[{id:"m6",from:"Elena Rossi",time:"Yesterday",body:"Just wanted to say the updated invoice came through. Everything looks right now — thank you for the quick fix!"}]},
];
const views = ["Open", "Assigned to me", "Snoozed", "Resolved"];
export default function Home() {
 const [tickets,setTickets]=useState(seed),[selected,setSelected]=useState("RL-2841"),[filter,setFilter]=useState("Open"),[query,setQuery]=useState(""),[reply,setReply]=useState(""),[note,setNote]=useState(false),[sent,setSent]=useState(false),[ready,setReady]=useState(false),[mobileOpen,setMobileOpen]=useState(false);
 useEffect(()=>{try{const data=localStorage.getItem("relay-tickets");if(data)setTickets(JSON.parse(data));}catch{}setReady(true);},[]);
 useEffect(()=>{if(ready)localStorage.setItem("relay-tickets",JSON.stringify(tickets));},[tickets,ready]);
 const current=tickets.find(t=>t.id===selected)??tickets[0];
 const shown=useMemo(()=>tickets.filter(t=>(filter!=="Resolved"||t.label==="Resolved")&&(filter==="Resolved"||t.label!=="Resolved")&&`${t.name} ${t.subject} ${t.preview}`.toLowerCase().includes(query.toLowerCase())),[tickets,filter,query]);
 const sendReply=(e:FormEvent)=>{e.preventDefault();if(!current||!reply.trim())return;const msg:Message={id:crypto.randomUUID(),from:note?"You · internal note":"You",time:"Just now",body:reply.trim(),...(note?{kind:"note" as const}:{})};setTickets(tickets.map(t=>t.id===current.id?{...t,messages:[...t.messages,msg],preview:reply.trim(),unread:false}:t));setReply("");setSent(true);setTimeout(()=>setSent(false),2200);};
 const resolve=()=>{if(!current)return;setTickets(tickets.map(t=>t.id===current.id?{...t,label:"Resolved",unread:false}:t));};
 if(!current)return <main className="empty-state"><Inbox/><h1>All caught up.</h1><p>Your inbox is clear. New conversations will land here.</p></main>;
 return <main className={`app-shell ${mobileOpen?"show-conversation":""}`}>
  <aside className="rail"><a className="mark" href="#" aria-label="Relay home"><span>r</span></a><nav aria-label="Primary navigation"><a className="rail-link selected" href="#inbox" aria-label="Inbox"><Inbox size={19}/><i/></a><a className="rail-link" href="#customers" aria-label="Customers"><Users size={19}/></a><a className="rail-link" href="#insights" aria-label="Insights"><Sparkles size={18}/></a></nav><div className="rail-bottom"><button className="rail-link" aria-label="Help"><CircleHelp size={18}/></button><button className="rail-link" aria-label="Settings"><Settings2 size={18}/></button><div className="my-avatar">SJ</div></div></aside>
  <aside className="inbox-sidebar"><div className="brand-row"><div><span className="brand-glyph">r</span><b>relay</b></div><button className="icon-btn" aria-label="More inbox actions"><MoreHorizontal size={19}/></button></div><button className="workspace-picker"><span className="workspace-dot">S</span><span><b>Studio North</b><small>Pro workspace</small></span><ChevronDown size={15}/></button><div className="inbox-heading"><span>INBOXES</span><button aria-label="Add inbox"><Plus size={15}/></button></div><div className="inbox-nav">{views.map((v,i)=><button key={v} className={`inbox-view ${filter===v?"active":""}`} onClick={()=>setFilter(v)}>{i===0?<Inbox size={16}/>:i===1?<AtSign size={16}/>:i===2?<Clock3 size={16}/>:<Check size={16}/>}<span>{v}</span><small>{i===0?tickets.filter(t=>t.label!=="Resolved").length:i===1?3:i===2?2:tickets.filter(t=>t.label==="Resolved").length}</small></button>)}</div><div className="inbox-heading channels"><span>CHANNELS</span><button aria-label="Add channel"><Plus size={15}/></button></div><div className="channel"><span className="channel-icon email"><AtSign size={14}/></span><span>Email</span><i/></div><div className="channel"><span className="channel-icon chat"><MessageMark/></span><span>Live chat</span><i/></div><div className="sidebar-bottom"><div className="teammate-row"><div className="avatar-small green">AL</div><div><b>Alex Lee</b><small>On your team</small></div><span className="online"/></div><div className="teammate-row"><div className="avatar-small purple">MK</div><div><b>Mei Kim</b><small>On your team</small></div><span className="online"/></div><button className="invite-button"><Plus size={15}/> Invite teammate</button></div></aside>
  <section className="queue" aria-label="Conversation list"><div className="queue-head"><div><div className="eyebrow">TUESDAY, OCTOBER 1</div><h1>{filter} <span>{shown.length}</span></h1></div><button className="icon-btn" aria-label="Queue options"><MoreHorizontal size={19}/></button></div><label className="queue-search"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search conversations"/><kbd>/</kbd></label><div className="queue-tools"><span>{tickets.filter(t=>t.unread&&t.label!=="Resolved").length} unread</span><button>Newest <ArrowDown size={13}/></button></div><div className="ticket-list">{shown.map(t=><button key={t.id} className={`ticket ${selected===t.id?"chosen":""}`} onClick={()=>{setSelected(t.id);setTickets(tickets.map(x=>x.id===t.id?{...x,unread:false}:x));setMobileOpen(true);}}><div className="ticket-top"><span className="customer-avatar" style={{background:t.color}}>{t.initials}</span><span className="customer-name">{t.name}</span><time>{t.time}</time></div><b className="ticket-subject">{t.subject}{t.priority&&<span className="priority-dot" aria-label="Priority"/>}</b><p>{t.preview}</p><div className="ticket-tags"><span className={`tag-label ${t.label.toLowerCase().replaceAll(" ","-")}`}>{t.label}</span><span className="ticket-id">{t.id}</span></div>{t.unread&&<i className="unread-dot"/>}</button>)}{shown.length===0&&<div className="no-results">No conversations found.</div>}</div><div className="queue-foot"><span><span className="live-dot"/> All systems operational</span><span>v1.0</span></div></section>
  <section className="conversation" aria-label={`Conversation with ${current.name}`}><header className="conversation-head"><div className="mobile-back"><button className="icon-btn" aria-label="Back to inbox" onClick={()=>setMobileOpen(false)}><ArrowLeft size={18}/></button></div><div><div className="eyebrow">{current.id} <span>·</span> RECEIVED 10:42 AM</div><h2>{current.subject}</h2></div><div className="conversation-actions"><button className="icon-btn" aria-label="Snooze conversation"><Clock3 size={17}/></button><button className="icon-btn" aria-label="More conversation actions"><MoreHorizontal size={19}/></button><button className="resolve-button" onClick={resolve}><Check size={15}/> Resolve</button></div></header>
   <div className="ticket-context"><div className="context-customer"><span className="customer-avatar big" style={{background:current.color}}>{current.initials}</span><div><b>{current.name}</b><span>{current.email}</span></div><button className="icon-btn" aria-label="View customer profile"><ArrowUpRight size={16}/></button></div><div className="context-meta"><div><span>ASSIGNEE</span><button className="assignee"><span className="avatar-small green">AL</span> Alex Lee <ChevronDown size={13}/></button></div><div><span>PRIORITY</span><button className="priority-select"><i/> {current.priority?"High":"Normal"}<ChevronDown size={13}/></button></div><div><span>TAG</span><button className="ticket-tag"><Tag size={12}/>{current.label}<ChevronDown size={13}/></button></div></div></div>
   <div className="sla-banner"><div className="sla-icon"><Clock3 size={15}/></div><span><b>First response due in 18 minutes</b><small>Priority conversations are answered within 1 hour.</small></span><button aria-label="SLA policy details"><ArrowUpRight size={14}/></button></div>
   <div className="thread"><div className="thread-day"><span/> TODAY, OCTOBER 1 <span/></div>{current.messages.map((m,i)=><article className={`message ${m.kind==="note"?"internal-note":""}`} key={m.id}><div className="message-avatar" style={{background:m.from.startsWith("You")?"#dce7f3":current.color}}>{m.from.startsWith("You")?"SJ":current.initials}</div><div className="message-body"><div className="message-head"><b>{m.from}</b>{m.kind&&<span className="internal-badge"><ShieldCheck size={12}/> Internal note</span>}<time>{m.time}</time></div><p>{m.body}</p>{i===0&&<button className="quoted-link"><Paperclip size={13}/> upgrade_receipt.pdf <ArrowUpRight size={12}/></button>}</div></article>)}<div className="event-line"><span/><p><b>Alex Lee</b> was assigned to this conversation <time>10:45 AM</time></p></div></div>
   <form className="composer" onSubmit={sendReply}><div className="composer-toolbar"><div className="reply-tabs"><button type="button" className={!note?"selected":""} onClick={()=>setNote(false)}><Send size={13}/> Reply</button><button type="button" className={note?"selected note-tab":""} onClick={()=>setNote(true)}><ShieldCheck size={13}/> Note</button></div><div className="composer-tools"><button type="button" aria-label="Attach file"><Paperclip size={15}/></button><button type="button" aria-label="Insert emoji"><Smile size={15}/></button><button type="button" aria-label="Insert saved reply"><Sparkles size={15}/></button></div></div><textarea aria-label={note?"Write an internal note":"Write a reply"} value={reply} onChange={e=>setReply(e.target.value)} placeholder={note?"Add a note for your team…":"Write a thoughtful reply…"}/><div className="composer-bottom"><span>{sent?<><Check size={13}/> Saved to this demo inbox</>:<><span className="keycap">⌘</span><span className="keycap">↵</span> to send</>}</span><button type="submit" className="send-button" disabled={!reply.trim()}>{note?"Add note":"Send reply"}<Send size={14}/></button></div></form>
  </section><aside className="detail-panel"><div className="detail-head"><b>Customer details</b><button className="icon-btn" aria-label="Close details"><X size={16}/></button></div><div className="customer-profile"><span className="customer-avatar profile-avatar" style={{background:current.color}}>{current.initials}</span><b>{current.name}</b><span>{current.email}</span><div className="profile-actions"><button><AtSign size={14}/> Email</button><button><ArrowUpRight size={14}/> Profile</button></div></div><div className="detail-section"><h3>ABOUT</h3><div className="detail-row"><span>Company</span><b>Brightpath Studio</b></div><div className="detail-row"><span>Location</span><b>Brooklyn, NY</b></div><div className="detail-row"><span>Customer since</span><b>May 2024</b></div></div><div className="detail-section"><h3>CONVERSATION HISTORY <span>4</span></h3><div className="history-row"><span className="history-dot blue"/><div><b>Payment question</b><small>Aug 18 · Resolved</small></div></div><div className="history-row"><span className="history-dot green"/><div><b>Invite a teammate</b><small>Jul 06 · Resolved</small></div></div><div className="history-row"><span className="history-dot lilac"/><div><b>Feature request</b><small>Jun 22 · Resolved</small></div></div><button className="history-link">View all conversations <ArrowUpRight size={13}/></button></div><div className="detail-section customer-tags"><h3>CUSTOMER TAGS <button aria-label="Add customer tag"><Plus size={13}/></button></h3><span>Pro plan</span><span>Team lead</span></div><div className="detail-footer"><span><Bell size={13}/> Customer notifications on</span><button aria-label="Change notification settings"><ChevronDown size={13}/></button></div></aside>
 </main>;
}
function MessageMark(){return <MessageCircleMore size={14}/>}

